[project]
name = "immo"
version = "0.1.0"
description = ""
authors = [
    {name = "zaslavsky", email = "zaslavsky@live.ru"}
]
requires-python = ">=3.10,<4"
dependencies = [
    "django (>=5.2,<6.0)",
    "django-environ (>=0.12.0,<0.13.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
